# Generated by Django 2.1.5 on 2020-03-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200321_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
