# Generated by Django 2.1.5 on 2020-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_userdata_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
